name: Test, Build, Release

on:
  push:
    branches: ["*"]
    tags:     ["v*"]
  pull_request:
    branches: [master]

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.4"
        bundler-cache: true

    - name: Run tests
      run: bundle exec rspec

  docker:
    runs-on: ubuntu-latest
    needs:   rspec
    if:      github.event_name == 'push'

    steps:
    - uses: actions/checkout@v4

    - uses: actions/github-script@v7
      id: set-tags
      with:
        script: |
          const ref = '${{ github.event.ref }}'
          const tags = ["latest", ref.substring(11)]

          const m = ref.match(/^refs\/tags\/v(\d+)\./)
          if (m) {
            tags.push(m[1])
          }
          return tags.join(",")
        result-encoding: string

    - name: Publish Docker image
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name:     ghcr.io/digineo/sisimai-web
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        tags:     ${{ steps.set-tags.outputs.result }}
