name: Test, Build, Release

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [master]
  release:
    types: [created]

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Setup bundler cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --

    - name: Run tests
      run: bundle exec rspec

  docker:
    runs-on: ubuntu-latest
    needs:   rspec

    steps:
    - name: Set image tag (for branches)
      if: startsWith(github.ref, 'refs/heads/')
      run: echo ::set-env name=IMAGE_TAG::$(echo ${GITHUB_REF:11})

    - name: Set image tag (for tags)
      if: startsWith(github.ref, 'refs/tags/')
      run: echo ::set-env name=IMAGE_TAG::$(echo ${GITHUB_REF:10})

    - name: Publish Docker image
      uses: elgohr/Publish-Docker-Github-Action@2.16
      with:
        name: digineode/sisimai-web
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ env.IMAGE_TAG }}"
