name: Test, Build, Release

on:
  push:
    branches: ["*"]
    tags:     ["v*"]
  pull_request:
    branches: [master]

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.7", "3.0", "3.1"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rspec

  docker:
    runs-on: ubuntu-latest
    needs:   rspec
    if:      github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2

    - uses: actions/github-script@v2
      id: set-tags
      with:
        script: |
          const ref = '${{ github.event.ref }}'
          const tags = ["latest", ref.substring(11)]

          const m = ref.match(/^refs\/tags\/v(\d+)\./)
          if (m) {
            tags.push(m[1])
          }
          return tags.join(",")
        result-encoding: string

    - name: Publish Docker image
      uses: elgohr/Publish-Docker-Github-Action@2.16
      with:
        name:     digineode/sisimai-web
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags:     ${{ steps.set-tags.outputs.result }}
